env: test

environment:
  testArg: tst
  slackUrl: ror-staging-slack-url
  projectId: ent-kub-tst
  pubsubTopic: projects/ent-kakka-tst/topics/ror.kakka.outbound.topic.geocoder.smoke.test
  gcsBasePath: gs://ror-kakka-test/es-data/
